# Use an NGINX base image to serve the static page
FROM nginx:alpine

# Copy the static content into the image
COPY ./index.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80

# Run NGINX server
CMD ["nginx", "-g", "daemon off;"]
